#!/bin/bash

# Portfolio Website Deployment Commands
# Copy and paste these commands in order

echo "=========================================="
echo "Portfolio System Deployment Guide"
echo "=========================================="
echo ""

# Step 1: Local Testing
echo "STEP 1: Local Testing"
echo "===================="
echo "Run these commands:"
echo ""
echo "cd app"
echo "npm install"
echo "npm run build"
echo "npm run dev"
echo ""
echo "✓ Open http://localhost:5173"
echo "✓ Verify site loads"
echo "✓ Test admin login at /admin"
echo ""
echo "Press Enter when ready for Step 2..."
read

# Step 2: Git Push
echo ""
echo "STEP 2: Push to GitHub"
echo "====================="
echo "Run these commands:"
echo ""
echo "cd .."
echo "git add ."
echo 'git commit -m "Deploy: Portfolio with admin panel and email marketing"'
echo "git push origin main"
echo ""
echo "✓ Wait for GitHub to process"
echo "✓ Verify changes are pushed"
echo ""
echo "Press Enter when ready for Step 3..."
read

# Step 3: Vercel Setup
echo ""
echo "STEP 3: Vercel Deployment"
echo "=========================="
echo ""
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click 'New Project'"
echo "3. Select repository: Mperomishael/mishael"
echo "4. Click 'Import'"
echo "5. Set Root Directory: app"
echo ""
echo "6. BEFORE CLICKING DEPLOY, add Environment Variables:"
echo ""
echo "   VITE_RESEND_API_KEY"
echo "   re_MenSLZEK_59dufN5BfjoLHEiMVt46HJGi"
echo ""
echo "   VITE_FIREBASE_API_KEY"
echo "   AIzaSyAwMt3l5FKjabNDpu8ybVwaAdKi2DqdYQw"
echo ""
echo "   VITE_FIREBASE_AUTH_DOMAIN"
echo "   mishael-port-folio.firebaseapp.com"
echo ""
echo "   VITE_FIREBASE_PROJECT_ID"
echo "   mishael-port-folio"
echo ""
echo "   VITE_FIREBASE_STORAGE_BUCKET"
echo "   mishael-port-folio.firebasestorage.app"
echo ""
echo "   VITE_FIREBASE_MESSAGING_SENDER_ID"
echo "   90852999870"
echo ""
echo "   VITE_FIREBASE_APP_ID"
echo "   1:90852999870:web:1664dcba497c022effd4ef"
echo ""
echo "   VITE_FIREBASE_MEASUREMENT_ID"
echo "   G-W9F0GG8Y6R"
echo ""
echo "7. Click 'Deploy'"
echo "8. Wait for build to complete (5-10 minutes)"
echo ""
echo "✓ Deployment complete!"
echo ""
echo "Press Enter for testing instructions..."
read

# Step 4: Post-Deployment Testing
echo ""
echo "STEP 4: Test Your Live Site"
echo "============================"
echo ""
echo "✓ Visit the Vercel URL from deployment"
echo "✓ Verify homepage loads"
echo "✓ Check portfolio sections"
echo "✓ Test contact info:"
echo "  - Phone: +2348142656848"
echo "  - WhatsApp: +2347086757575"
echo "  - Email: empiredigitalsworldwide@gmail.com"
echo "✓ Test newsletter signup in footer"
echo "✓ Test admin login at /admin"
echo "  - Email: empiredigitalsworldwide@gmail.com or letstalk2mishael@gmail.com"
echo "✓ Check for console errors (F12)"
echo ""
echo "=========================================="
echo "Deployment Complete! 🎉"
echo "=========================================="
echo ""
echo "Your portfolio is now live!"
echo ""
echo "Next Steps:"
echo "1. Login to admin panel"
echo "2. Add portfolio projects"
echo "3. Monitor email subscriptions"
echo "4. Share your site!"
echo ""
